[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.zip", "php82Extensions.bcmath", "composer"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-interaction --ignore-platform-reqs"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"